add tiny proxy. move all services to /etc/service/, fix openvpn route

diff --git a/app/openvpn/run b/app/openvpn/run
--- a/app/openvpn/run
+++ b/app/openvpn/run
@@ -11,34 +11,34 @@ export NORDVPN_PROTOCOL
 NORDVPN_CATEGORY=${NORDVPN_CATEGORY:-P2P}
 export NORDVPN_CATEGORY
 
-VPN_PROVIDER_HOME=/app/openvpn/nordvpn/
+VPN_PROVIDER_HOME=/etc/service/openvpn/nordvpn/
 export VPN_PROVIDER_HOME
 
-. /app/date.sh --source-only
+. /etc/service/date.sh --source-only
 # Create a tun device see: https://www.kernel.org/doc/Documentation/networking/tuntap.txt
 if [ ! -c /dev/net/tun ]; then
-    echo "$(adddate) INFO: OVPN: Creating tun interface /dev/net/tun"
+    log "INFO: OVPN: Creating tun interface /dev/net/tun"
     mkdir -p /dev/net
     mknod /dev/net/tun c 10 200
     chmod 600 /dev/net/tun
 fi
 
-cd /app/openvpn/nordvpn/
+cd ${VPN_PROVIDER_HOME}
 nbFiles=0
 
 ./configure-openvpn.sh
-nbFiles=$(ls -1 *.ovpn | grep -c ovpn)
-confFile=$(ls -1 *.ovpn | grep -v default.ovpn)
+nbFiles=$(ls -1 ${VPN_PROVIDER_HOME}/*.ovpn | grep -c ovpn)
+confFile=$(ls -1 ${VPN_PROVIDER_HOME}/*.ovpn | grep -v default.ovpn)
 echo ########################################################
-echo "$(adddate) INFO: OVPN: Files found: $nbFiles"
-echo "$(adddate) INFO: OVPN: Current load: $LOAD"
-#echo "$(adddate) INFO: OVPN: Info updated at: $UPDATED_AT"
-#echo "$(adddate) INFO: OVPN: Server IP: $IP"
-echo "$(adddate) INFO: OVPN: config: $confFile"
+log "INFO: OVPN: Files found: $nbFiles"
+log "INFO: OVPN: Current load: $LOAD"
+#log "INFO: OVPN: Info updated at: $UPDATED_AT"
+#log "INFO: OVPN: Server IP: $IP"
+log "INFO: OVPN: config: $confFile"
 echo ########################################################
 
 if [[ ${nbFiles} -eq 0 ]]; then
-    echo "$(adddate) ERROR: OVPN: No OpenVPN config found in $(pwd)/. Exiting."
+    log "ERROR: OVPN: No OpenVPN config found in $(pwd)/. Exiting."
     exit 1
 fi
 
@@ -48,7 +48,7 @@ sed -i "s/^ping.*//g" "$confFile"
 echo "inactive 3600" >>"$confFile"
 echo "ping 10" >>"$confFile"
 echo "ping-exit 60" >>"$confFile"
-echo -e "script-security 2\nup /app/openvpn/up.sh\ndown /app/openvpn/down.sh" >>"$confFile"
+echo -e "management localhost 7505\nscript-security 2\n--up /etc/service/openvpn/up.sh\n--down /etc/service/openvpn/down.sh" >>"$confFile"
 
 #Use secrets if present
 if [ -e /run/secrets/NORDVPN_LOGIN ]; then
@@ -66,22 +66,33 @@ fi
 # add OpenVPN user/pass
 if [[ "${NORDVPN_LOGIN}" == "**None**" ]] || [[ "${NORDVPN_PASS}" == "**None**" ]]; then
     if [[ ! -f /config/openvpn-credentials.txt ]]; then
-        echo "$(adddate) ERROR: OVPN: OpenVPN credentials not set. Exiting."
+        log "ERROR: OVPN: OpenVPN credentials not set. Exiting."
         exit 1
     fi
-    echo "$(adddate) INFO: OVPN: Found existing OPENVPN credentials at /config/openvpn-credentials.txt"
+    log "INFO: OVPN: Found existing OPENVPN credentials at /config/openvpn-credentials.txt"
 else
-    echo "$(adddate) INFO: OVPN: Setting OpenVPN credentials..."
+    log "INFO: OVPN: Setting OpenVPN credentials..."
     mkdir -p /config
     echo "${NORDVPN_LOGIN}" >/config/openvpn-credentials.txt
     echo "${NORDVPN_PASS}" >>/config/openvpn-credentials.txt
     chmod 600 /config/openvpn-credentials.txt
-    sed -i "s#auth-user-pass.*#auth-user-pass /config/openvpn-credentials.txt#g" "/app/openvpn/nordvpn/${confFile}"
-    [[ $DEBUG -eq 1 ]] && cat /app/openvpn/nordvpn/${confFile} || true
+    sed -i "s#auth-user-pass.*#auth-user-pass /config/openvpn-credentials.txt#g" "${confFile}"
+    [[ $DEBUG -eq 1 ]] && cat ${confFile} || true
 fi
 
-openvpn /app/openvpn/nordvpn/${confFile}
+#echo "export LOCAL_NETWORK=${LOCAL_NETWORK}" > /tmp/vars
+eval $(/sbin/ip route list match 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}')
+echo "LOCAL_NETWORK: ${LOCAL_NETWORK}, Gateway: ${GW}, device ${INT}"
+if [[ -n ${LOCAL_NETWORK:-""} ]]; then
+  if [[ -n ${GW:-""} ]] && [[ -n ${INT:-""} ]]; then
+    for localNet in ${LOCAL_NETWORK//,/ }; do
+      echo "adding route to local network ${localNet} via ${GW} dev ${INT}"
+      /sbin/ip route add "${localNet}" via "${GW}" dev "${INT}"
+    done
+  fi
+fi
+openvpn --config ${confFile}
 
-echo "$(adddate) INFO: OVPN: VPN connection lost, stopping unbound"
-echo "$(adddate) INFO: OVPN: Waiting ${waitSec} seconds before restarting"
+log "INFO: OVPN: VPN connection lost, stopping unbound"
+log "INFO: OVPN: Waiting ${waitSec} seconds before restarting"
 sleep ${waitSec}
